kakeibo/urls.py
from django.urls import path
from .views import PaymentList, IncomeList, PaymentCreate, IncomeCreate,PaymentCategoryCreate ,PaymentUpdate, IncomeUpdate, PaymentDelete, IncomeDelete, MonthDashboard

app_name = "kakeibo"

urlpatterns = [
    path('', PaymentList.as_view(), name="payment_list"),
    path("income_list/", IncomeList.as_view(), name="income_list"),
    path("payment_create/", PaymentCreate.as_view(), name="payment_create"),
    path("income_create/", IncomeCreate.as_view(), name="income_create"),
    path("payment_category_create/", PaymentCategoryCreate.as_view(), name="payment_category_create"),
    path('payment_update/<int:pk>/', PaymentUpdate.as_view(), name='payment_update'),
    path('income_update/<int:pk>/', IncomeUpdate.as_view(), name='income_update'),
    path('payment_delete/<int:pk>/', PaymentDelete.as_view(), name='payment_delete'),
    path('income_delete/<int:pk>/', IncomeDelete.as_view(), name='income_delete'),
    #月別に表示したいので、yearとmonthを指定します。
    path('month_dashboard/<int:year>/<int:month>/', MonthDashboard.as_view(), name='month_dashboard'),
]

kakeiboproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("kakeibo.urls")),
]

kakeibo/models.py
from django.db import models

# Create your models here.


#カテゴリ名を保存するためのモデル
class PaymentCategory(models.Model):
    name = models.CharField("カテゴリ名", max_length=32)

    #カテゴリ名を入力されたものをそのまま返すようにしている。
    def __str__(self):
        return self.name


class Payment(models.Model):
    date = models.DateField("日付")
    price = models.IntegerField("金額")
    """
    on_delete=models.PROTECT	は結びついている子データがある場合は親データを削除できない
    
    ForeignKeyは多対1の多の子側につけられるもの。
    ForeignKey(紐づけるモデル名, on_delete=親フィールドが削除されたときの動作, **options)

    下記の例では、
    PaymentはPaymentCategoryの子側としてモデル（テーブル）同士の関係性を結びつけている。
    """
    """verbose_name='○○'は
     verbose_nameの扱い方について
モデルにおいて指定する場所でそれぞれ変更するものが違う。
・メタデータ内での指定:モデル名の変更
・フィールド内での指定:フィールド名の変更

詳しくは以下参照
https://office54.net/python/django/model-verbose-name
    """
    category = models.ForeignKey(PaymentCategory,
                                 on_delete=models.PROTECT,
                                 verbose_name="カテゴリ")
    description = models.TextField('摘要', null=True, blank=True)


#以下、Incomeにおいても同じコード。
class IncomeCategory(models.Model):
    name = models.CharField('カテゴリ名', max_length=32)

    def __str__(self):
        return self.name


class Income(models.Model):
    date = models.DateField('日付')
    price = models.IntegerField('金額')
    category = models.ForeignKey(IncomeCategory,
                                 on_delete=models.PROTECT,
                                 verbose_name='カテゴリ')
    description = models.TextField('摘要', null=True, blank=True)

register/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    pass

kakeibo/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, TemplateView
from django.shortcuts import render, redirect
from .models import Payment, PaymentCategory, Income, IncomeCategory
from .forms import PaymentSearchForm, IncomeSearchForm, PaymentCreateForm, IncomeCreateForm, PaymentCategoryCreateForm
from django.contrib import messages
import numpy as np
import pandas as pd
from django_pandas.io import read_frame
from .plugin_plotly import GraphGenerator

# Create your views here.

class PaymentList(ListView):
    template_name = "kakeibo/payment_list.html"
    model = Payment
    ordering = "-date"
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        self.form = form = PaymentSearchForm(self.request.GET or None)

        if form.is_valid():
            year = form.cleaned_data.get('year')
            # 何も選択されていないときは0の文字列が入るため、除外
            if year and year != '0':
                queryset = queryset.filter(date__year=year)

            month = form.cleaned_data.get('month')
            # 何も選択されていないときは0の文字列が入るため、除外
            if month and month != '0':
                queryset = queryset.filter(date__month=month)

            # 〇〇円以上の絞り込み
            greater_than = form.cleaned_data.get('greater_than')
            if greater_than:
                queryset = queryset.filter(price__gte=greater_than)

            # 〇〇円以下の絞り込み
            less_than = form.cleaned_data.get('less_than')
            if less_than:
                queryset = queryset.filter(price__lte=less_than)

            # キーワードの絞り込み
            key_word = form.cleaned_data.get('key_word')
            if key_word:
                # 空欄で区切り、順番に絞る、and検索
                if key_word:
                    for word in key_word.split():
                        queryset = queryset.filter(description__icontains=word)

            # カテゴリでの絞り込み
            category = form.cleaned_data.get('category')
            if category:
                queryset = queryset.filter(category=category)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # search formを渡す
        context['search_form'] = self.form

        return context

class IncomeList(ListView):
    template_name = "kakeibo/income_list.html"
    model = Income
    ordering = "-date"
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        self.form = form = IncomeSearchForm(self.request.GET or None)

        if form.is_valid():
            year = form.cleaned_data.get('year')
            # 何も選択されていないときは0の文字列が入るため、除外
            if year and year != '0':
                queryset = queryset.filter(date__year=year)

            month = form.cleaned_data.get('month')
            # 何も選択されていないときは0の文字列が入るため、除外
            if month and month != '0':
                queryset = queryset.filter(date__month=month)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # search formを渡す
        context['search_form'] = self.form

        return context

"""支出と登録のhtmlをregister.htmlで共有している。"""
class PaymentCreate(CreateView):
    """支出登録"""
    template_name = 'kakeibo/register.html'
    model = Payment
    form_class = PaymentCreateForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = '支出登録'
        return context

    def get_success_url(self):
        return reverse_lazy('kakeibo:payment_list')

     # バリデーション時にメッセージを保存
    def form_valid(self, form):
        self.object = payment = form.save()
        messages.info(self.request,
                      f'支出を登録しました\n'
                      f'日付:{payment.date}\n'
                      f'カテゴリ:{payment.category}\n'
                      f'金額:{payment.price}円')
        return redirect(self.get_success_url())

class PaymentCategoryCreate(CreateView):
    """支出カテゴリ登録"""
    template_name = 'kakeibo/register.html'
    model = PaymentCategory
    form_class = PaymentCategoryCreateForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = '支出カテゴリ登録'
        return context

    def get_success_url(self):
        return reverse_lazy('kakeibo:payment_list')
    
    def form_valid(self, form):
        self.object = payment_category = form.save()
        messages.info(self.request,
                    f'カテゴリを追加しました\n'
                    f'カテゴリ:{payment_category.name}')
        return redirect(self.get_success_url())

class IncomeCreate(CreateView):
    """収入登録"""
    template_name = 'kakeibo/register.html'
    model = Income
    form_class = IncomeCreateForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = '収入登録'
        return context

    def get_success_url(self):
        return reverse_lazy('kakeibo:income_list')

     # バリデーション時にメッセージを保存
    def form_valid(self, form):
        self.object = income = form.save()
        messages.info(self.request,
                      f'収入を登録しました\n'
                      f'日付:{income.date}\n'
                      f'カテゴリ:{income.category}\n'
                      f'金額:{income.price}円')
        return redirect(self.get_success_url())

class PaymentUpdate(UpdateView):
    """支出更新"""
    template_name = 'kakeibo/register.html'
    model = Payment
    form_class = PaymentCreateForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = '支出更新'
        return context

    def get_success_url(self):
        return reverse_lazy('kakeibo:payment_list')

    def form_valid(self, form):
        self.object = payment = form.save()
        messages.info(self.request,
                      f'支出を更新しました\n'
                      f'日付:{payment.date}\n'
                      f'カテゴリ:{payment.category}\n'
                      f'金額:{payment.price}円')
        return redirect(self.get_success_url())


class IncomeUpdate(UpdateView):
    """収入更新"""
    template_name = 'kakeibo/register.html'
    model = Income
    form_class = IncomeCreateForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = '収入更新'
        return context

    def get_success_url(self):
        return reverse_lazy('kakeibo:income_list')

    def form_valid(self, form):
        self.object = income = form.save()
        messages.info(self.request,
                      f'収入を更新しました\n'
                      f'日付:{income.date}\n'
                      f'カテゴリ:{income.category}\n'
                      f'金額:{income.price}円')
        return redirect(self.get_success_url())


class PaymentDelete(DeleteView):
    """支出削除"""
    template_name = 'kakeibo/delete.html'
    model = Payment

    def get_success_url(self):
        return reverse_lazy('kakeibo:payment_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = '支出削除確認'

        return context

    def delete(self, request, *args, **kwargs):
        self.object = payment = self.get_object()

        payment.delete()

        return redirect(self.get_success_url())


class IncomeDelete(DeleteView):
    """収入削除"""
    template_name = 'kakeibo/delete.html'
    model = Income

    def get_success_url(self):
        return reverse_lazy('kakeibo:income_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = '収入削除確認'

        return context

    def delete(self, request, *args, **kwargs):
        self.object = income = self.get_object()
        income.delete()

        return redirect(self.get_success_url())

class MonthDashboard(TemplateView):
    """月間支出ダッシュボード"""
    template_name = "kakeibo/month_dashboard.html"

    """考察:おそらく、共通コンテキストを作成した時点で、
    def get_context_data(self, **kwargs)
    で呼び出している、context内に追加されており、

    context = super().get_context_data(**kwargs)
    ですべてのコンテキスト内のデータを集めきっている。
    urls.pyで引数に渡されているyear,monthのデータも、そのうちの一つ。
    """

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        #これから表示する年月
        year = int(self.kwargs.get('year'))
        month = int(self.kwargs.get('month'))
        context['year_month'] = f'{year}年{month}月'

        #前月と次月をコンテキストに入れて渡す
        if month == 1:
            prev_year = year - 1
            prev_month = 12
        else:
            prev_year = year
            prev_month = month - 1

        if month == 12:
            next_year = year + 1
            next_month = 1
        else:
            next_year = year
            next_month = month + 1
        
        context['prev_year'] = prev_year
        context['prev_month'] = prev_month
        context['next_year'] = next_year
        context['next_month'] = next_month

        # paymentモデルをdfにする.
        #年➡月の順にデータをフィルタリング
        pay_queryset = Payment.objects.filter(date__year=year)
        pay_queryset = pay_queryset.filter(date__month=month)
        
        income_queryset = Income.objects.filter(date__year=year)
        income_queryset = income_queryset.filter(date__month=month)

        # income、payそれぞれのクエリセットがある時ない時で場合分けをし、contextを返す
        # 後の工程でエラーになるため
        if not pay_queryset and not income_queryset:
            context['total_payment'] = 0
            context['total_income'] = 0
            context['total_savings'] = 0
            return context
        
        elif not pay_queryset and income_queryset:
            df_income = read_frame(income_queryset, fieldnames=["date", "price", "category"])
            context['total_income'] = df_income['price'].sum()
            context['total_payment'] = 0
            context['total_savings'] = df_income['price'].sum()

register/views.py
from django.shortcuts import render

# Create your views here.

kakeibo/templates/kakeibo/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>家計簿アプリ</title>
  <link rel="stylesheet" href="{% static 'kakeibo/css/reset.css' %}">
  <link rel="stylesheet" href="{% static 'kakeibo/css/style.css' %}">
  {% block extrajs %}{% endblock %}
</head>

<body>
  <header class="page-header">
    <h1>
      <a href="{% url 'kakeibo:payment_list' %}" class="header-title">家計簿アプリ</a>
    </h1>
    <nav class="nav">
      <ul class="main-nav ml-5">
        <li class="ml-5">
          <a href="{% url 'kakeibo:payment_list'%}">支出一覧</a>
        </li>
        <li class="ml-5">
          <a href="{% url 'kakeibo:income_list'%}">収入一覧</a>
        </li>
        <li class="ml-5">
          <a href="{% url 'kakeibo:payment_create'%}">支出登録</a>
        </li>
        <li class="ml-5">
          <a href="{% url 'kakeibo:income_create'%}">収入登録</a>
        </li>
        </li>
        <li class="ml-5">
          <a href="{% url 'kakeibo:payment_category_create'%}">支出カテゴリ登録</a>
        </li>
        <li class="ml-5">
          <a href="{% url 'kakeibo:month_dashboard' now_year now_month %}">月間収支</a>
        </li>
    </nav>
  </header>

  <div class="layout">
    <div class="container">
      <main>
        <!-- メッセージがある場合は表示する -->
        {% if messages %}
        <div class="alert alert-success js-alert" id="js-alert">
          <button class="alert-btn-close js-alert-close" type="button">ｘ</button>
          <!-- メッセージを取り出す -->
          {% for message in messages %}
          <p> {{ message|linebreaks }}</p>
          {% endfor %}
        </div>
        {% endif %}
        {% block content %}{% endblock %}
      </main>
    </div>
  </div>

</body>

<script type="text/javascript">
  // ×を押して閉じられるようにする
  for (const element of document.querySelectorAll('.js-alert > .js-alert-close')) {
    element.addEventListener('click', e => {
      e.target.parentElement.classList.add('is-hidden');
    });
  }
</script>


</html>

kakeibo/templates/kakeibo/delete.html
{% extends 'kakeibo/base.html' %}

{% block content %}
<h1>{{ page_title }}</h1>
<p class="mt-5"> 本当に削除してよろしいですか？</p>

<p class="mt-4">日付：{{ object.date }}</p>
<p class="mt-4">カテゴリ：{{ object.category }}</p>
<p class="mt-4">金額：{{ object.price }}</p>
<p class="mt-4">摘要： {% if object.description %}{{ object.description }}{% endif %}</p>

<form class="mt-4" method="post">
  {% csrf_token %}
  <!-- ページタイトルから戻ろ一覧を分岐 -->
  {% if '支出' in page_title %}
  <a class="btn btn-info" href="{% url 'kakeibo:payment_list'%}">
    いいえ、一覧に戻ります
  </a>
  {% else %}
  <a class="btn btn-info" href="{% url 'kakeibo:income_list'%}">
    いいえ、一覧に戻ります
  </a>
  {% endif %}
  <button type="submit" class="btn btn-danger">
    はい、削除します
  </button>
</form>

{% endblock %}

kakeibo/templates/kakeibo/income_list.html
{% extends 'kakeibo/base.html' %}
{% load humanize %}
{% load kakeibo %}
{% block content %}

<form class="mt-2" id="search-form" action="" method="GET">
  <label class="label mr-4">年月</label>
  {{ search_form.year }}
  {{ search_form.month }}
  <button class="btn btn-info ml-4" type="submit">検索</button>
</form>

<p class="search-result mt-3">{{ page_obj.paginator.count }}件の検索結果</p>

<table class="table mt-3">
  <tr>
    <th>日付</th>
    <th>カテゴリ</th>
    <th>金額</th>
    <th>摘要</th>
    <th>編集</th>
  </tr>
  {% for income in income_list %}

  <tr>
    <td>{{ income.date }}</td>
    <td>{{ income.category }}</td>
    <td>{{ income.price|intcomma}}</td>
    <td>
      {% if income.description %}
      {{ income.description }}
      {% endif %}
    </td>
    <td>
      <div class="manage-btn-area">
        <div class="update-btn-area">
          <a class="btn btn-info" href="{% url 'kakeibo:income_update' income.pk %}">更新</a>
        </div>
        <div class="delete-btn-area">
          <a class="btn btn-danger" href="{% url 'kakeibo:income_delete' income.pk %}">削除</a>
        </div>
      </div>
    </td>
  </tr>
  {% endfor %}
</table>

<!--ページネーション-->
{% include 'kakeibo/include/pagination.html' %}

{% endblock %}

kakeibo/templates/kakeibo/month_dashboard.html
{% extends 'kakeibo/base.html' %}
{% load humanize %}
{% block content %}

<div class="month-pager">
  <a href="{% url 'kakeibo:month_dashboard' prev_year prev_month %}">
    前月
  </a>
  <span class="ml-4 mr-4">{{ year_month }}</span>
  <a href="{% url 'kakeibo:month_dashboard' next_year next_month %}">
    次月
  </a>
</div>

{% autoescape off %}
<div class="month-dash-page-top mt-4">
  <div class="left card">
    <table class="table">
      <tr>
        <th>カテゴリ</th>
        <th>金額</th>
      </tr>
      <!--keyはindexカラムに指定したカテゴリ、valueはpriceカラムのカテゴリごとの金額-->
      {% for key,value in table_set_pay.items %}
      <tr>
        <td>{{ key }}</td>
        <td>{{ value|intcomma }}</td>
      </tr>
      {% endfor %}
      <tr>
        <td>支出合計</td>
        <td>{{ total_payment|intcomma }}</td>
      </tr>
      <tr>
        <td>収入合計</td>
        <td>{{ total_income|intcomma }}</td>
      </tr>
      <tr class="result-month">
        <td>月間収支</td>
        <td>{{ total_savings|intcomma }}</td>
      </tr>
    </table>
  </div>
  <div class="right ml-4 hidden_toolbar">
    {{ plot_pie }}
  </div>
</div>
<div class="month-dash-bottom">
  {{ plot_bar }}
</div>
{% endautoescape %}

{% endblock %}

{% block extrajs %}
<!-- plotlyのjs -->
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
{% endblock %}

kakeibo/templates/kakeibo/payment_list.html
{% extends "kakeibo/base.html" %}
{% load humanize %}
{% load kakeibo %}
{% block content %}

<!--検索フォーム-->
<form class="mt-2" id="search-form" action="" method="GET">
  <div>
    <label class="label mr-4">年月</label>
    {{ search_form.year }}
    {{ search_form.month }}
  </div>
  <div class="mt-4">
    <label class="label mr-4">金額</label>
    {{ search_form.greater_than }}
    <span class="ml-4 mr-4">～</span>
    {{ search_form.less_than }}
  </div>
  <div class="mt-4">
    {{ search_form.key_word }}
    <button class="btn btn-info ml-4" type="submit">検索</button>
  </div>
  <div class="mt-2 inline">
    {{ search_form.category }}
  </div>
</form>

<!--追加　表示件数-->
<p class="search-result mt-3">{{ page_obj.paginator.count }}件の検索結果</p>

<table class="table mt-3">
  <tr>
    <th>日付</th>
    <th>カテゴリ</th>
    <th>金額</th>
    <th>摘要</th>
    <th>編集</th>
  </tr>

  <!--urls.pyファイル内でname="payment_list"と
    逆からの参照ができるようにしていたものをinに利用している-->
  {% for payment in payment_list %}

  <tr>
    <td>{{ payment.date }}</td>
    <td>{{ payment.category }}</td>
    <td>{{ payment.price|intcomma}}</td>
    <td>
      {% if payment.description %}
      {{ payment.description }}
      {% endif %}
    </td>
    <td>
      <div class="manage-btn-area">
        <div class="update-btn-area">
          <a class="btn btn-info" href="{% url 'kakeibo:payment_update' payment.pk %}">更新</a>
        </div>
        <div class="delete-btn-area">
          <a class="btn btn-danger" href="{% url 'kakeibo:payment_delete' payment.pk %}">削除</a>
        </div>
      </div>
    </td>
  </tr>
  {% endfor %}
</table>

<!-- ページネーション -->
{% include 'kakeibo/include/pagination.html' %}

{% endblock %}

kakeibo/templates/kakeibo/register.html
{% extends "kakeibo/base.html" %}

{% block content %}
<h1>{{ page_title }}</h1>
<form method="POST">{% csrf_token %}
  {{ form.non_field_errors }}
  {% for field in form %}
  <div class="mt-4">
    {{ field }}
    {{ field.errors }}
  </div>
  {% endfor %}
  <button class="btn mt-4" type="submit" name="button">送信</button>
</form>

<!-- date picker -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/themes/base/jquery-ui.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<script type="text/javascript">
  $(function () {
    $('#id_date').datepicker({
      dateFormat: 'yy-mm-dd',
      firstDay: 1,
      dayNamesMin: ["日", "月", "火", "水", "木", "金", "土"],
      monthNames: ["1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "9月", "10月", "11月", "12月"],
    });
  })
</script>

{% endblock %}